language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install requests==2.7.0
  - pip install coveralls==0.5
  - pip install travis-sphinx
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  #ignore line too long in flake8 (flake8 doesn't support Python 2.6 anymore)
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install flake8==3.3.0;flake8 --ignore E501 .; fi
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
script:
  - PYTHONPATH=$PYTHONPATH:. coverage run --source=clevertimapi --rcfile=.coveragerc setup.py test -v
  - coverage combine
  - coverage report
  - travis-sphinx
  - travis-sphinx deploy
after_success:
    coveralls --rcfile=.coveragerc
