language: python
python:
  - "2.6"
  - "2.7"
install:
    - pip install requests==2.7.0
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script: python setup.py test
